[package]
name = "aoba"
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
version.workspace = true
edition.workspace = true
build = "build.rs"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
cfg-if.workspace = true
derive_more.workspace = true
num_enum.workspace = true
once_cell.workspace = true
parking_lot.workspace = true

base64.workspace = true
bytes.workspace = true
chrono.workspace = true
percent-encoding.workspace = true
sqids.workspace = true

serde.workspace = true
serde_json.workspace = true
postcard.workspace = true
strum.workspace = true
toml.workspace = true
uuid.workspace = true
yuuka.workspace = true
rand.workspace = true

clap.workspace = true
env_logger.workspace = true
log.workspace = true
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true

flume.workspace = true
tokio.workspace = true
futures.workspace = true
oneshot.workspace = true

whoami.workspace = true
crossterm.workspace = true

image.workspace = true
eframe.workspace = true
egui.workspace = true
ratatui.workspace = true
unicode-width.workspace = true

rmodbus.workspace = true
libc.workspace = true
serialport.workspace = true
interprocess.workspace = true

expectrl.workspace = true
regex.workspace = true
vt100.workspace = true
ctrlc.workspace = true

aoba_cli = { path = "../cli" }
aoba_protocol = { path = "../protocol" }

[dev-dependencies]
tokio-test.workspace = true

aoba_ci_utils = { path = "../ci_utils" }

[features]
_tui_ui_test = []

[build-dependencies]
anyhow.workspace = true
serde_json.workspace = true
toml.workspace = true
semver.workspace = true
