[package]
name = "aoba_protocol"
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
cfg-if.workspace = true
derive_more.workspace = true
once_cell.workspace = true
parking_lot.workspace = true

base64.workspace = true
bytes.workspace = true
chrono.workspace = true
percent-encoding.workspace = true
sqids.workspace = true

serde.workspace = true
serde_json.workspace = true
postcard.workspace = true
strum.workspace = true
toml.workspace = true
uuid.workspace = true
yuuka.workspace = true
rand.workspace = true

log.workspace = true
tracing.workspace = true

flume.workspace = true
futures.workspace = true
tokio.workspace = true

rmodbus.workspace = true
libc.workspace = true
serialport.workspace = true
interprocess.workspace = true

regex.workspace = true
whoami.workspace = true
