[[dependencies]]
name = "anyhow"
version = ""

[[dependencies]]
name = "async-trait"
version = ""

[[dependencies]]
name = "base64"
version = ""

[[dependencies]]
name = "bytes"
version = ""

[[dependencies]]
name = "cfg-if"
version = ""

[[dependencies]]
name = "chrono"
version = ""

[[dependencies]]
name = "clap"
version = ""

[[dependencies]]
name = "crossterm"
version = ""

[[dependencies]]
name = "ctrlc"
version = ""

[[dependencies]]
name = "derive_more"
version = ""

[[dependencies]]
name = "eframe"
version = ""

[[dependencies]]
name = "egui"
version = ""

[[dependencies]]
name = "env_logger"
version = ""

[[dependencies]]
name = "expectrl"
version = ""

[[dependencies]]
name = "flume"
version = ""

[[dependencies]]
name = "futures"
version = ""

[[dependencies]]
name = "image"
version = ""

[[dependencies]]
name = "interprocess"
version = ""

[[dependencies]]
name = "libc"
version = ""

[[dependencies]]
name = "log"
version = ""

[[dependencies]]
name = "num_enum"
version = ""

[[dependencies]]
name = "once_cell"
version = ""

[[dependencies]]
name = "oneshot"
version = ""

[[dependencies]]
name = "parking_lot"
version = ""

[[dependencies]]
name = "percent-encoding"
version = ""

[[dependencies]]
name = "postcard"
version = ""

[[dependencies]]
name = "rand"
version = ""

[[dependencies]]
name = "ratatui"
version = ""

[[dependencies]]
name = "regex"
version = ""

[[dependencies]]
name = "rmodbus"
version = ""

[[dependencies]]
name = "serde"
version = ""

[[dependencies]]
name = "serde_json"
version = ""

[[dependencies]]
name = "serialport"
version = ""

[[dependencies]]
name = "sqids"
version = ""

[[dependencies]]
name = "strum"
version = ""

[[dependencies]]
name = "tokio"
version = ""

[[dependencies]]
name = "toml"
version = ""

[[dependencies]]
name = "tracing"
version = ""

[[dependencies]]
name = "tracing-appender"
version = ""

[[dependencies]]
name = "tracing-subscriber"
version = ""

[[dependencies]]
name = "unicode-width"
version = ""

[[dependencies]]
name = "uuid"
version = ""

[[dependencies]]
name = "vt100"
version = ""

[[dependencies]]
name = "whoami"
version = ""

[[dependencies]]
name = "yuuka"
version = ""

[license_map]
anyhow = "MIT OR Apache-2.0"
async-trait = "MIT OR Apache-2.0"
base64 = "MIT OR Apache-2.0"
bytes = "MIT"
cfg-if = "MIT OR Apache-2.0"
chrono = "MIT OR Apache-2.0"
clap = "MIT OR Apache-2.0"
crossterm = "MIT"
ctrlc = "MIT/Apache-2.0"
derive_more = "MIT"
eframe = "MIT OR Apache-2.0"
egui = "MIT OR Apache-2.0"
env_logger = "MIT OR Apache-2.0"
expectrl = "MIT"
flume = "Apache-2.0/MIT"
futures = "MIT OR Apache-2.0"
image = "MIT OR Apache-2.0"
interprocess = "MIT OR Apache-2.0"
libc = "MIT OR Apache-2.0"
log = "MIT OR Apache-2.0"
num_enum = "BSD-3-Clause OR MIT OR Apache-2.0"
once_cell = "MIT OR Apache-2.0"
oneshot = "MIT OR Apache-2.0"
parking_lot = "MIT OR Apache-2.0"
percent-encoding = "MIT OR Apache-2.0"
postcard = "MIT OR Apache-2.0"
rand = "MIT OR Apache-2.0"
ratatui = "MIT"
regex = "MIT OR Apache-2.0"
rmodbus = "Apache-2.0"
serde = "MIT OR Apache-2.0"
serde_json = "MIT OR Apache-2.0"
serialport = "MPL-2.0"
sqids = "MIT"
strum = "MIT"
tokio = "MIT"
toml = "MIT OR Apache-2.0"
tracing = "MIT"
tracing-appender = "MIT"
tracing-subscriber = "MIT"
unicode-width = "MIT OR Apache-2.0"
uuid = "Apache-2.0 OR MIT"
vt100 = "MIT"
whoami = "Apache-2.0 OR BSL-1.0 OR MIT"
yuuka = "Apache-2.0"

[package]
name = "aoba"
