name: "Test Preparation"
description: "Prepare environment for E2E tests"

inputs:
  need_gui_deps:
    description: "Whether to install GUI dependencies"
    required: false
    default: "false"
  need_ports:
    description: "Whether to setup virtual serial ports"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: target/debug/

    - name: Make binaries executable
      run: |
        chmod +x target/debug/aoba
        chmod +x target/debug/cli_e2e
        chmod +x target/debug/tui_e2e
      shell: bash

    - name: Install system dependencies
      if: inputs.need_gui_deps == 'true'
      run: |
        sudo apt-get update
        sudo apt-get install -y libudev-dev pkg-config libx11-dev libxcb-shape0-dev libxcb-xfixes0-dev socat
      shell: bash

    - name: Setup virtual serial ports
      if: inputs.need_ports == 'true'
      run: |
        chmod +x scripts/socat_init.sh
        ./scripts/socat_init.sh
      shell: bash
