name: CI Basic Checks

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

env:
  CARGO_TERM_COLOR: always

jobs:
  examples-check:
    name: Check examples/**
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [aoba_cli_integration_tests, aoba_tui_integration_tests]

    steps:
      - uses: actions/checkout@v5

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libudev-dev pkg-config libx11-dev libxcb-shape0-dev libxcb-xfixes0-dev

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Run fmt check for package
        run: cargo fmt -p ${{ matrix.package }} -- --check

      - name: Run cargo check for package
        run: cargo check -p ${{ matrix.package }} --all-targets --all-features

      - name: Run clippy for package
        run: cargo clippy -p ${{ matrix.package }} --all-targets --all-features -- -D warnings
