name: "Copilot Setup Steps"

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      # Use stable Rust for consistent smoke test results
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      # Install system dependencies (socat no longer needed for virtual ports)
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libudev-dev pkg-config libx11-dev libxcb-shape0-dev libxcb-xfixes0-dev

      # Cache Cargo registry for faster builds
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: copilot-env-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            copilot-env-cargo-

      # Test the environment to ensure everything works
      # Note: Environment uses existing ttyS devices present in CI
      - name: Test environment (sanity checks)
        run: |
          rustc --version || true
          cargo --version || true

          # Quick cargo check (non-failing to avoid CI breakage)
          cargo check --all-targets || true

          # Verify serial ports are available for testing
          echo "Available serial ports for testing:"
          find /dev -name "ttyS*" | head -5

      # Clean up virtual ports/processes (ensure socat is killed if started)
      - name: Cleanup
        if: always()
        run: |
          if [ ! -z "$SOCAT_PID" ]; then
            sudo kill $SOCAT_PID || true
          fi

          if [ -e /dev/ttyV1 ]; then
            sudo rm -f /dev/ttyV1 || true
          fi
          if [ -e /dev/ttyV2 ]; then
            sudo rm -f /dev/ttyV2 || true
          fi
