name: Copilot Setup Steps

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libudev-dev pkg-config libx11-dev libxcb-shape0-dev libxcb-xfixes0-dev socat

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: copilot-env-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            copilot-env-cargo-

      - name: Setup virtual serial ports
        run: |
          chmod +x examples/tui_e2e_tests/scripts/socat_init.sh
          sudo examples/tui_e2e_tests/scripts/socat_init.sh

      - name: Cleanup virtual ports
        if: always()
        run: |
          # Kill socat processes if they exist
          sudo pkill socat || true

          # Remove virtual port links if they exist
          sudo rm -f /dev/vcom1 /dev/vcom2 || true
