name: E2E Tests

on:
  push:
    branches: [master, dev]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  # Single setup job that builds everything and prepares for testing (reusable)
  setup:
    uses: ./.github/workflows/reusable-setup.yml
    with:
      install_rust: true
      rust_toolchain: stable
      install_deps: gui
      build_packages: |
        aoba
        cli_e2e
        tui_e2e
      upload_artifacts: true
      artifacts: |
        target/debug/aoba
        target/debug/cli_e2e
        target/debug/tui_e2e

  # CLI E2E Basic tests (no vcom needed)
  cli-e2e-basic:
    name: CLI E2E Basic - ${{ matrix.module }}
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module:
          - help
          - list_ports
          - list_ports_json
          - list_ports_status
          - modbus_basic_master_slave

    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/test-prep
        with:
          need_gui_deps: false
          need_ports: ${{ matrix.module == 'modbus_basic_master_slave' }}

      - name: Run CLI E2E module
        run: ./target/debug/cli_e2e --module ${{ matrix.module }}

      - name: Cleanup virtual ports
        if: matrix.module == 'modbus_basic_master_slave' && always()
        run: |
          pkill socat || true
          rm -f /tmp/vcom1 /tmp/vcom2 || true

  # CLI E2E Config Mode tests (multi-masters and multi-slaves)
  cli-e2e-config-mode:
    name: CLI E2E Config Mode - ${{ matrix.module }}
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module:
          - modbus_multi_masters
          - modbus_multi_masters_same_station
          - modbus_multi_slaves
          - modbus_multi_slaves_same_station
          - modbus_multi_slaves_adjacent_registers

    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/test-prep
        with:
          need_gui_deps: false
          need_ports: true

      - name: Run CLI E2E module
        run: ./target/debug/cli_e2e --module ${{ matrix.module }}

      - name: Cleanup virtual ports
        if: always()
        run: |
          pkill socat || true
          rm -f /tmp/vcom1 /tmp/vcom2 || true

  # TUI E2E Single-Station Master Mode tests
  tui-e2e-single-master:
    name: TUI E2E Single Master - ${{ matrix.module }}
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module:
          - tui_master_coils
          - tui_master_discrete_inputs
          - tui_master_holding
          - tui_master_input

    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/test-prep
        with:
          need_gui_deps: true
          need_ports: true

      - name: Run TUI E2E module
        run: ./target/debug/tui_e2e --module ${{ matrix.module }}

      - name: Cleanup virtual ports
        if: always()
        run: |
          pkill socat || true
          rm -f /tmp/vcom1 /tmp/vcom2 || true

  # TUI E2E Single-Station Slave Mode tests
  tui-e2e-single-slave:
    name: TUI E2E Single Slave - ${{ matrix.module }}
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module:
          - tui_slave_coils
          - tui_slave_discrete_inputs
          - tui_slave_holding
          - tui_slave_input

    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/test-prep
        with:
          need_gui_deps: true
          need_ports: true

      - name: Run TUI E2E module
        run: ./target/debug/tui_e2e --module ${{ matrix.module }}

      - name: Cleanup virtual ports
        if: always()
        run: |
          pkill socat || true
          pkill aoba || true
          rm -f /tmp/vcom1 /tmp/vcom2 || true

  # TUI E2E Multi-Station Master Mode tests
  tui-e2e-multi-master:
    name: TUI E2E Multi Master - ${{ matrix.module }}
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module:
          - tui_multi_master_mixed_types
          - tui_multi_master_spaced_addresses
          - tui_multi_master_mixed_ids

    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/test-prep
        with:
          need_gui_deps: true
          need_ports: true

      - name: Run TUI E2E module
        run: ./target/debug/tui_e2e --module ${{ matrix.module }}

      - name: Cleanup virtual ports
        if: always()
        run: |
          pkill socat || true
          pkill aoba || true
          rm -f /tmp/vcom1 /tmp/vcom2 || true

  # TUI E2E Multi-Station Slave Mode tests
  tui-e2e-multi-slave:
    name: TUI E2E Multi Slave - ${{ matrix.module }}
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module:
          - tui_multi_slave_mixed_types
          - tui_multi_slave_spaced_addresses
          - tui_multi_slave_mixed_ids

    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/test-prep
        with:
          need_gui_deps: true
          need_ports: true

      - name: Run TUI E2E module
        run: ./target/debug/tui_e2e --module ${{ matrix.module }}

      - name: Cleanup virtual ports
        if: always()
        run: |
          pkill socat || true
          pkill aoba || true
          rm -f /tmp/vcom1 /tmp/vcom2 || true
