name: E2E Tests

on:
  push:
    branches: [master, dev]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  e2e-test:
    name: E2E Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example: [cli_e2e, tui_e2e]

    steps:
      - uses: actions/checkout@v5

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y libudev-dev pkg-config libx11-dev libxcb-shape0-dev libxcb-xfixes0-dev socat

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build test dependencies
        run: |
          cargo build --bin aoba

      - name: Setup virtual serial ports
        run: |
          chmod +x scripts/socat_init.sh
          ./scripts/socat_init.sh

      - name: Run E2E tests
        run: |
          cargo run --example ${{ matrix.example }}

      - name: Cleanup virtual ports
        if: always()
        run: |
          # Kill socat processes if they exist
          pkill socat || true

          # Remove virtual port links if they exist
          rm -f /tmp/vcom1 /tmp/vcom2 /tmp/aoba_vcom* || true
