name: TUI UI E2E Tests

on:
  push:
    branches: [master, dev]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  tui-ui-e2e:
    name: TUI UI E2E - ${{ matrix.module }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module:
          - tui_ui_entry_navigation
          - tui_ui_modbus_panel_shortcuts
          - tui_ui_status_bar_rendering

    steps:
      - uses: actions/checkout@v5

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libudev-dev pkg-config libx11-dev libxcb-shape0-dev libxcb-xfixes0-dev

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: tui-ui-e2e-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            tui-ui-e2e-cargo-

      - name: Build packages
        run: cargo build --package aoba --package tui_ui_e2e

      - name: Make binaries executable
        run: |
          chmod +x target/debug/aoba
          chmod +x target/debug/tui_ui_e2e

      - name: Run TUI UI E2E module
        run: ./target/debug/tui_ui_e2e --module ${{ matrix.module }}
