# Smoke tests with virtual serial ports for black-box CLI testing
# These tests validate basic functionality quickly without deep integration
name: Smoke Tests

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

env:
  CARGO_TERM_COLOR: always

jobs:
  smoke-test:
    name: Smoke Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Use stable Rust for consistent smoke test results
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      # Install system dependencies including socat for virtual serial ports
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libudev-dev pkg-config libx11-dev libxcb-shape0-dev libxcb-xfixes0-dev socat

      # Cache Cargo registry to speed up builds
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      # Build release binaries for testing
      - name: Build release binaries
        run: cargo build --release

      # Set up virtual serial ports
      # Creates /dev/ttyV1 and /dev/ttyV2 connected to each other
      - name: Setup virtual serial ports
        run: |
          # Start socat as root so it can create device nodes under /dev
          sudo socat -d -d pty,raw,echo=0,link=/dev/ttyV1 pty,raw,echo=0,link=/dev/ttyV2 &
          SOCAT_PID=$!
          echo "SOCAT_PID=$SOCAT_PID" >> $GITHUB_ENV

          # Wait for device files to appear (timeout after 10s)
          for i in {1..10}; do
            if [ -e /dev/ttyV1 ] && [ -e /dev/ttyV2 ]; then
              break
            fi
            sleep 1
          done

          # Double-check existence and try to change permissions as sudo to avoid Permission denied
          if [ -e /dev/ttyV1 ] && [ -e /dev/ttyV2 ]; then
            sudo chmod 666 /dev/ttyV1 /dev/ttyV2 || true
          else
            echo "Virtual serial devices not created: /dev/ttyV1 or /dev/ttyV2 missing"
            ps aux | grep socat || true
            exit 1
          fi

      # Run the dedicated smoke test binary and CLI integration tests example
      - name: Run smoke tests
        run: |
          # Run our dedicated smoke test binary
          cargo run --bin smoke_test

          # Run CLI integration tests example
          cargo run --example cli_integration_tests

      # Clean up virtual ports
      - name: Cleanup
        if: always()
        run: |
          if [ ! -z "$SOCAT_PID" ]; then
            kill $SOCAT_PID || true
          fi
