name: TUI E2E Tests

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

env:
  CARGO_TERM_COLOR: always

jobs:
  tui-e2e-test:
    name: TUI E2E Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libudev-dev pkg-config libx11-dev libxcb-shape0-dev libxcb-xfixes0-dev socat

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build test dependencies
        run: |
          cargo build

      - name: Setup virtual serial ports
        run: |
          chmod +x examples/tui_e2e_tests/scripts/socat_init.sh
          sudo examples/tui_e2e_tests/scripts/socat_init.sh

      - name: Enumerate serial ports (diagnostic)
        run: |
          echo "=== Running port enumeration diagnostic ==="
          cargo run --example enumerate_ports

      - name: Run TUI E2E tests
        run: |
          cargo run -p aoba_tui_e2e_tests --bin tui_e2e_tests

      - name: Cleanup virtual ports
        if: always()
        run: |
          # Kill socat processes if they exist
          sudo pkill socat || true

          # Remove virtual port links if they exist
          sudo rm -f /dev/vcom1 /dev/vcom2 || true
